### ISSUE TITLE
--delete-excluded and --delete flags are always set

### ISSUE THREAD

**Issue by dudewad** [jedrichards/grunt-rsync#43]
options: {
        args: ["--verbose --perms --chmod=0755"],
        exclude: [".git*", ".DS_Store", ".htaccess"],
        ssh: true,
        recursive: true,
        syncDest: true,
        compareMode: "checksum"
    },

    staging: {
        options: {
            src: "./dist/",
            dest: "/var/www/html/staging",
	        host: "somehost",
	        deleteAll: false,
	        delete:false
        }
    }

Using the two above config option sets, I get any files not present in my dist folder deleted.
The following is output at the end:

Shell command was: rsync ./dist/ admin@somehost.com:/var/www/html/staging --rsh ssh --recursive --delete --delete-excluded --exclude=.git* --exclude=.DS_Store --exclude=.htaccess --checksum --verbose --perms --chmod=0755 
OK

This is problematic, seeing as how I *dont* want to delete everything that's not in my dist directory. .htaccess gets blown away despite being on my exclusion list.
Thoughts?
I've tried every combination of delete: false, deleteAll false etc etc.

**Comment by jedrichards** [comment]
I think its because you still have a `syncDest` flag in there.

We removed it from the documentation and replaced it with the more scary sounding `deleteAll` flag. But we left `syncDest` in the code for legacy reasons, so old configs would continue to work. `syncDest` and `deleteAll` both do the same thing, i.e. set the `--delete --delete-excluded` flags.

Remove `syncDest` and you should be good.

**Comment by dudewad** [comment]
Oh my. Silly me. Such is the life of inheriting code :) 
Thanks

**Comment by jedrichards** [comment]
No probs :)
