### ISSUE TITLE
question about host

### ISSUE THREAD

**Issue by littlebee** [jedrichards/grunt-rsync#49]
Can you pass an array of hosts?   For example, I have a single staging host and 3 production hosts.

**Comment by jedrichards** [comment]
Afaik there's no in-built way to add multiple destinations to a single rsync command. I could be wrong about that, but I'm fairly sure there isn't. For example the answer to this Q just suggests using a loop:

http://superuser.com/questions/722237/rsync-to-multiple-directories-with-one-command

It's been awhile since I've done any Grunt, and my Grunt config fu is weak, but could you achieve what you need by making multiple Grunt tasks and sharing some config between them? You could potentially run those tasks in parallel to speed things up? https://github.com/sindresorhus/grunt-concurrent

**Comment by littlebee** [comment]
Yeah, no big deal, I can work with that and, if you had said yes, my next question was going to be, can it do it concurrently.
Thanks for the work on this and the quick reply!
I'm curious what you are using now for building and why you switched.  It's beginning to feel like a town where all the factories closed here in Gruntville :)

**Comment by jedrichards** [comment]
I switched to just using npm-run scripts having read blog posts like this,

http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/

I like the approach because it cuts down on the number of dependencies you need (i.e. you just need the main CLI tool, not a Grunt plugin for it too). I also felt like a set of npm scripts could be more concise and maintainable than Grunt configs when they get to a certain size.

A problem with npm scripts though is that they can get quite _dense_ for complex tasks though, and your team needs strong command line skills. But aside from that I'm happy with my switch.
