### ISSUE TITLE
Prototype Pollution/Dep Issue w/Lodash

### ISSUE THREAD

**Issue by johndugan** [jedrichards/grunt-rsync#55]
Just getting started with grunt-rsync. Thanks for it!

Looks like the lodash dependency could be bumped up to a more recent version.

![grunt-rsync](https://user-images.githubusercontent.com/1389303/41236335-7ebd74d8-6d56-11e8-9f17-bc83bd9c9b47.png)

**Comment by jedrichards** [comment]
We'll have to update this in rsyncwrapper, since that's the package using lodash.

https://github.com/jedrichards/rsyncwrapper

In fact, it'd probably be fairly feasible to remove the lodash dependency entirely using modern Node language features.

I'll leave this issue open as a reminder to bump the rsyncwrapper dependency when done.

**Comment by jedrichards** [comment]
rsyncwrapper issue https://github.com/jedrichards/rsyncwrapper/issues/51

**Comment by jvinai** [comment]
Do you have an idea of when you will update lodash dependency ?

**Comment by jedrichards** [comment]
@johndugan @jvinai I've just published version `3.0.0` of this package that removes the lodash dependency completely and relies on plain JS instead.
